// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Adjustment struct {
	ID        int64
	CreatedAt string
	BeforeID  int64
	AfterID   int64
	TurnsA    float64
	TurnsB    float64
	TurnsC    float64
	PredDcx   float64
	PredDcy   float64
	ObsDcx    float64
	ObsDcy    float64
	Applied   float64
	Status    string
}

type Calibration struct {
	ID        int64
	CreatedAt string
	Source    string
	ACx       float64
	ACy       float64
	BCx       float64
	BCy       float64
	CCx       float64
	CCy       float64
	ASx       float64
	ASy       float64
	BSx       float64
	BSy       float64
	CSx       float64
	CSy       float64
	CMeasured int64
}

type Measurement struct {
	ID            int64
	CreatedAt     string
	Kind          string
	ComaX         float64
	ComaY         float64
	ComaErr       float64
	AxisXMm       float64
	AxisYMm       float64
	DecentreMm    float64
	SeeingPx      float64
	Obstruction   float64
	SaPx          float64
	StepUm        float64
	ParaxialFocus float64
	Alt           float64
	Az            float64
	FocTemp       float64
	AmbTemp       float64
	Stars         int64
	Frames        int64
	Files         string
	RefFocpos     int64
	Positions     string
	AfterSlew     int64
	Note          string
}

type Setting struct {
	Key   string
	Value string
}
