// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const completeAdjustment = `-- name: CompleteAdjustment :exec
UPDATE adjustments
SET after_id = ?, obs_dcx = ?, obs_dcy = ?, applied = ?, status = 'done'
WHERE id = ?
`

type CompleteAdjustmentParams struct {
	AfterID int64
	ObsDcx  float64
	ObsDcy  float64
	Applied float64
	ID      int64
}

func (q *Queries) CompleteAdjustment(ctx context.Context, arg CompleteAdjustmentParams) error {
	_, err := q.db.ExecContext(ctx, completeAdjustment,
		arg.AfterID,
		arg.ObsDcx,
		arg.ObsDcy,
		arg.Applied,
		arg.ID,
	)
	return err
}

const createAdjustment = `-- name: CreateAdjustment :exec
INSERT INTO adjustments (created_at, before_id, turns_a, turns_b, turns_c, pred_dcx, pred_dcy)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAdjustmentParams struct {
	CreatedAt string
	BeforeID  int64
	TurnsA    float64
	TurnsB    float64
	TurnsC    float64
	PredDcx   float64
	PredDcy   float64
}

func (q *Queries) CreateAdjustment(ctx context.Context, arg CreateAdjustmentParams) error {
	_, err := q.db.ExecContext(ctx, createAdjustment,
		arg.CreatedAt,
		arg.BeforeID,
		arg.TurnsA,
		arg.TurnsB,
		arg.TurnsC,
		arg.PredDcx,
		arg.PredDcy,
	)
	return err
}

const createCalibration = `-- name: CreateCalibration :exec
INSERT INTO calibrations (
    created_at, source, a_cx, a_cy, b_cx, b_cy, c_cx, c_cy,
    a_sx, a_sy, b_sx, b_sy, c_sx, c_sy, c_measured
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCalibrationParams struct {
	CreatedAt string
	Source    string
	ACx       float64
	ACy       float64
	BCx       float64
	BCy       float64
	CCx       float64
	CCy       float64
	ASx       float64
	ASy       float64
	BSx       float64
	BSy       float64
	CSx       float64
	CSy       float64
	CMeasured int64
}

func (q *Queries) CreateCalibration(ctx context.Context, arg CreateCalibrationParams) error {
	_, err := q.db.ExecContext(ctx, createCalibration,
		arg.CreatedAt,
		arg.Source,
		arg.ACx,
		arg.ACy,
		arg.BCx,
		arg.BCy,
		arg.CCx,
		arg.CCy,
		arg.ASx,
		arg.ASy,
		arg.BSx,
		arg.BSy,
		arg.CSx,
		arg.CSy,
		arg.CMeasured,
	)
	return err
}

const createMeasurement = `-- name: CreateMeasurement :exec
INSERT INTO measurements (
    created_at, kind, coma_x, coma_y, coma_err, axis_x_mm, axis_y_mm, decentre_mm,
    seeing_px, obstruction, sa_px, step_um, paraxial_focus, alt, az, foc_temp, amb_temp,
    stars, frames, files, ref_focpos, positions, after_slew, note,
    tilt_x, tilt_y, tilt_err, shadow_x_mm, shadow_y_mm, hub_x_mm, hub_y_mm, pupil_err_mm, intra_high,
    tilt_rough, pupil_rough
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMeasurementParams struct {
	CreatedAt     string
	Kind          string
	ComaX         float64
	ComaY         float64
	ComaErr       float64
	AxisXMm       float64
	AxisYMm       float64
	DecentreMm    float64
	SeeingPx      float64
	Obstruction   float64
	SaPx          float64
	StepUm        float64
	ParaxialFocus float64
	Alt           float64
	Az            float64
	FocTemp       float64
	AmbTemp       float64
	Stars         int64
	Frames        int64
	Files         string
	RefFocpos     int64
	Positions     string
	AfterSlew     int64
	Note          string
	TiltX         float64
	TiltY         float64
	TiltErr       float64
	ShadowXMm     float64
	ShadowYMm     float64
	HubXMm        float64
	HubYMm        float64
	PupilErrMm    float64
	IntraHigh     int64
	TiltRough     int64
	PupilRough    int64
}

func (q *Queries) CreateMeasurement(ctx context.Context, arg CreateMeasurementParams) error {
	_, err := q.db.ExecContext(ctx, createMeasurement,
		arg.CreatedAt,
		arg.Kind,
		arg.ComaX,
		arg.ComaY,
		arg.ComaErr,
		arg.AxisXMm,
		arg.AxisYMm,
		arg.DecentreMm,
		arg.SeeingPx,
		arg.Obstruction,
		arg.SaPx,
		arg.StepUm,
		arg.ParaxialFocus,
		arg.Alt,
		arg.Az,
		arg.FocTemp,
		arg.AmbTemp,
		arg.Stars,
		arg.Frames,
		arg.Files,
		arg.RefFocpos,
		arg.Positions,
		arg.AfterSlew,
		arg.Note,
		arg.TiltX,
		arg.TiltY,
		arg.TiltErr,
		arg.ShadowXMm,
		arg.ShadowYMm,
		arg.HubXMm,
		arg.HubYMm,
		arg.PupilErrMm,
		arg.IntraHigh,
		arg.TiltRough,
		arg.PupilRough,
	)
	return err
}

const getCurrentCalibration = `-- name: GetCurrentCalibration :one
SELECT id, created_at, source, a_cx, a_cy, b_cx, b_cy, c_cx, c_cy, a_sx, a_sy, b_sx, b_sy, c_sx, c_sy, c_measured FROM calibrations ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetCurrentCalibration(ctx context.Context) (Calibration, error) {
	row := q.db.QueryRowContext(ctx, getCurrentCalibration)
	var i Calibration
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Source,
		&i.ACx,
		&i.ACy,
		&i.BCx,
		&i.BCy,
		&i.CCx,
		&i.CCy,
		&i.ASx,
		&i.ASy,
		&i.BSx,
		&i.BSy,
		&i.CSx,
		&i.CSy,
		&i.CMeasured,
	)
	return i, err
}

const getLastMeasurementID = `-- name: GetLastMeasurementID :one
SELECT CAST(COALESCE(MAX(id), 0) AS INTEGER) AS id FROM measurements
`

func (q *Queries) GetLastMeasurementID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastMeasurementID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMeasurement = `-- name: GetMeasurement :one
SELECT id, created_at, kind, coma_x, coma_y, coma_err, axis_x_mm, axis_y_mm, decentre_mm, seeing_px, obstruction, sa_px, step_um, paraxial_focus, alt, az, foc_temp, amb_temp, stars, frames, files, ref_focpos, positions, after_slew, note, tilt_x, tilt_y, tilt_err, shadow_x_mm, shadow_y_mm, hub_x_mm, hub_y_mm, pupil_err_mm, intra_high, tilt_rough, pupil_rough FROM measurements WHERE id = ?
`

func (q *Queries) GetMeasurement(ctx context.Context, id int64) (Measurement, error) {
	row := q.db.QueryRowContext(ctx, getMeasurement, id)
	var i Measurement
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Kind,
		&i.ComaX,
		&i.ComaY,
		&i.ComaErr,
		&i.AxisXMm,
		&i.AxisYMm,
		&i.DecentreMm,
		&i.SeeingPx,
		&i.Obstruction,
		&i.SaPx,
		&i.StepUm,
		&i.ParaxialFocus,
		&i.Alt,
		&i.Az,
		&i.FocTemp,
		&i.AmbTemp,
		&i.Stars,
		&i.Frames,
		&i.Files,
		&i.RefFocpos,
		&i.Positions,
		&i.AfterSlew,
		&i.Note,
		&i.TiltX,
		&i.TiltY,
		&i.TiltErr,
		&i.ShadowXMm,
		&i.ShadowYMm,
		&i.HubXMm,
		&i.HubYMm,
		&i.PupilErrMm,
		&i.IntraHigh,
		&i.TiltRough,
		&i.PupilRough,
	)
	return i, err
}

const getPendingAdjustment = `-- name: GetPendingAdjustment :one
SELECT id, created_at, before_id, after_id, turns_a, turns_b, turns_c, pred_dcx, pred_dcy, obs_dcx, obs_dcy, applied, status FROM adjustments WHERE status = 'pending' ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetPendingAdjustment(ctx context.Context) (Adjustment, error) {
	row := q.db.QueryRowContext(ctx, getPendingAdjustment)
	var i Adjustment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.BeforeID,
		&i.AfterID,
		&i.TurnsA,
		&i.TurnsB,
		&i.TurnsC,
		&i.PredDcx,
		&i.PredDcy,
		&i.ObsDcx,
		&i.ObsDcy,
		&i.Applied,
		&i.Status,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listMeasurementsSince = `-- name: ListMeasurementsSince :many
SELECT id, created_at, kind, coma_x, coma_y, coma_err, axis_x_mm, axis_y_mm, decentre_mm, seeing_px, obstruction, sa_px, step_um, paraxial_focus, alt, az, foc_temp, amb_temp, stars, frames, files, ref_focpos, positions, after_slew, note, tilt_x, tilt_y, tilt_err, shadow_x_mm, shadow_y_mm, hub_x_mm, hub_y_mm, pupil_err_mm, intra_high, tilt_rough, pupil_rough FROM measurements
WHERE created_at >= ? AND kind IN ('measure', 'calibrate')
ORDER BY id
`

func (q *Queries) ListMeasurementsSince(ctx context.Context, createdAt string) ([]Measurement, error) {
	rows, err := q.db.QueryContext(ctx, listMeasurementsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measurement
	for rows.Next() {
		var i Measurement
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Kind,
			&i.ComaX,
			&i.ComaY,
			&i.ComaErr,
			&i.AxisXMm,
			&i.AxisYMm,
			&i.DecentreMm,
			&i.SeeingPx,
			&i.Obstruction,
			&i.SaPx,
			&i.StepUm,
			&i.ParaxialFocus,
			&i.Alt,
			&i.Az,
			&i.FocTemp,
			&i.AmbTemp,
			&i.Stars,
			&i.Frames,
			&i.Files,
			&i.RefFocpos,
			&i.Positions,
			&i.AfterSlew,
			&i.Note,
			&i.TiltX,
			&i.TiltY,
			&i.TiltErr,
			&i.ShadowXMm,
			&i.ShadowYMm,
			&i.HubXMm,
			&i.HubYMm,
			&i.PupilErrMm,
			&i.IntraHigh,
			&i.TiltRough,
			&i.PupilRough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAdjustments = `-- name: ListRecentAdjustments :many
SELECT id, created_at, before_id, after_id, turns_a, turns_b, turns_c, pred_dcx, pred_dcy, obs_dcx, obs_dcy, applied, status FROM adjustments ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListRecentAdjustments(ctx context.Context, limit int64) ([]Adjustment, error) {
	rows, err := q.db.QueryContext(ctx, listRecentAdjustments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Adjustment
	for rows.Next() {
		var i Adjustment
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.BeforeID,
			&i.AfterID,
			&i.TurnsA,
			&i.TurnsB,
			&i.TurnsC,
			&i.PredDcx,
			&i.PredDcy,
			&i.ObsDcx,
			&i.ObsDcy,
			&i.Applied,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMeasurements = `-- name: ListRecentMeasurements :many
SELECT id, created_at, kind, coma_x, coma_y, coma_err, axis_x_mm, axis_y_mm, decentre_mm, seeing_px, obstruction, sa_px, step_um, paraxial_focus, alt, az, foc_temp, amb_temp, stars, frames, files, ref_focpos, positions, after_slew, note, tilt_x, tilt_y, tilt_err, shadow_x_mm, shadow_y_mm, hub_x_mm, hub_y_mm, pupil_err_mm, intra_high, tilt_rough, pupil_rough FROM measurements ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListRecentMeasurements(ctx context.Context, limit int64) ([]Measurement, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMeasurements, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measurement
	for rows.Next() {
		var i Measurement
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Kind,
			&i.ComaX,
			&i.ComaY,
			&i.ComaErr,
			&i.AxisXMm,
			&i.AxisYMm,
			&i.DecentreMm,
			&i.SeeingPx,
			&i.Obstruction,
			&i.SaPx,
			&i.StepUm,
			&i.ParaxialFocus,
			&i.Alt,
			&i.Az,
			&i.FocTemp,
			&i.AmbTemp,
			&i.Stars,
			&i.Frames,
			&i.Files,
			&i.RefFocpos,
			&i.Positions,
			&i.AfterSlew,
			&i.Note,
			&i.TiltX,
			&i.TiltY,
			&i.TiltErr,
			&i.ShadowXMm,
			&i.ShadowYMm,
			&i.HubXMm,
			&i.HubYMm,
			&i.PupilErrMm,
			&i.IntraHigh,
			&i.TiltRough,
			&i.PupilRough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT key, value FROM settings ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const skipPendingAdjustments = `-- name: SkipPendingAdjustments :exec
UPDATE adjustments SET status = 'skipped' WHERE status = 'pending'
`

func (q *Queries) SkipPendingAdjustments(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, skipPendingAdjustments)
	return err
}
